employees/urls.py
from django.urls import path
from .views import (
    employees_list,
    employees_delete,
    employees_update,
    get_employee_info
)


app_name = 'employees'


urlpatterns = [
    path('list/', employees_list, name='employees_list'),
    path('delete/', employees_delete, name='employees_delete'),
    path('update/', employees_update, name='employees_update'),
    path('info/', get_employee_info, name='get_employee_info'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('employees/', include('employees.urls', namespace='employees')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

employees/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)

    def __str__(self):
        return str(self.first_name + ' ' + self.last_name)

employees/forms.py
from django import forms
from django.forms import fields
from .models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

employees/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import Employee
from .forms import EmployeeForm

# Create your views here.

# Update Employees View.
def employees_update(request):
    data = {}
    if request.is_ajax() and request.method == 'POST':

        # get the data send from the Browser.
        get_id = request.POST.get('id')
        get_first_name = request.POST.get('first_name')
        get_last_name = request.POST.get('last_name')

        # get the Employee have the same info.
        get_employee = Employee.objects.get(id=get_id)

        # if found the employee.
        if get_employee:

            # change the first_name of ths employee.
            get_employee.first_name = get_first_name

            # change the last_name of this employee.
            get_employee.last_name = get_last_name

            # save the change.
            get_employee.save()

            # set the response inside a dictionry
            data['update_success'] = 'Employee has been update his info'

            # send the response to the Browser
            return JsonResponse(data)

        # if not found the employee
        else:

            # set the response inside a dictionry
            data['update_error'] = 'Employee info not update'

            # send the response to the Browser
            return JsonResponse(data)
  
        



# function to get the employee info.
def get_employee_info(request):
    data = {}
    if request.is_ajax() and request.method == 'POST':
        
        # get the id it was send by the Browser using ajax.
        get_id = int(request.POST.get('id'))

        # get the Employee have The same ID.
        get_employee = Employee.objects.get(id=get_id)

        # if found the Employee
        if get_employee:
            # set the response inside a dictionry
            data['id'] = get_employee.id
            data['first_name'] = get_employee.first_name
            data['last_name'] = get_employee.last_name

            # send the response to the Browser.
            return JsonResponse(data)





# Remove Employees View.
def employees_delete(request):
    data = {}
    if request.is_ajax() and request.method == 'POST':

        get_id = int(request.POST.get('id'))
        getEmployee = Employee.objects.get(id=get_id)

        # if Employee is Found.
        if getEmployee:

            # delete the employee was found.
            getEmployee.delete()

            # set the response inside a dictionry
            data['delete_success'] = 'Employee has Been deleted'

            # send the response to the Browser.
            return JsonResponse(data)

        # if the Employee not found.
        else:

            # set the response inside a dictionry
            data['delete_employee_error'] = 'Employee not deleted try again'

            # send the response to the Browser.
            return JsonResponse(data)





# Employees List View.
def employees_list(request):
    form = EmployeeForm()
    data = {}
    # get all employee in database.
    employees = Employee.objects.all()

    if request.is_ajax() and request.method == 'POST':
        # put the request inside form.
        form = EmployeeForm(request.POST)

        # find the Employee.
        getEmployee = Employee.objects.filter(first_name=request.POST['first_name'], last_name=request.POST['last_name']).exists()

        # if the form is valid.
        if form.is_valid():

            # if the employee is found.
            if not getEmployee:
                
                # save the form.
                form.save()
                # set the response inside a dictionry
                data['success'] = 'Employee Has Been Add'

                # send the response to the Browser.
                return JsonResponse(data)
            else:
                # set the response inside a dictionry
                data['error'] = 'Employee already exists'

                # send the response to the Browser.
                return JsonResponse(data)
        else:
            # set the response inside a dictionry
            data['error'] = 'Oops! someThing Is Wrong, Try again'

            # send the response to the Browser.
            return JsonResponse(data)

    # The context.
    context = {
        'form': form,
        'developer': 'Mohammed ELkhamlichi',
        'employees': employees,
    }
    return render(request, 'employees/employees_list.html', context)

employees/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap Link-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- page Title -->
    {% block css %}
      
    {% endblock%}
    <title>Management</title>
</head>
<body class="bg-dark">
    <!-- nav bar -->
    {% include "navbar.html" %}
    {% block navbar %}
      
    {% endblock %}


    <!-- content -->
    <div class="container bg-light mt-4">
        {% block content %}
        
        {% endblock %}    
    </div>

    <!-- js scripts -->
    <script src="{% static 'clients/jquery-3.5.1.min.js' %}"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.js"></script> -->
    {% block js %}

    {% endblock%}
</body>
</html>

employees/templates/employees/employees_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    {% for message in messages%}
        {{message}}
    {% endfor %}
    <div id="alert-box"></div>
    <form action="" id="form">
        {% csrf_token %}
        <div class="form-group">
            {{ form.first_name|as_crispy_field}}
        </div>
        <div class="form-group">
            {{ form.last_name|as_crispy_field}}
        </div>
        <center>
            <style>
                .hide{
                    display:none;
                }
            </style>
            <input type="button" id="form_add_employee" value="Add Employee" class="btn btn-success mt-3 mb-3"> 
            <input type="button" id="form_update_employee" value="Update Employee" class="btn btn-info  hide mt-3 mb-3"> 

        </center>
    </form>
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Remove</th>
                <th>Update</th>
            </tr>
        </thead>
        <tbody id="tbody-list">
            <style>
                .hide{
                    display:none;
                }
            </style>
            {% for employee in employees %}
            <tr>
                <td>{{ employee.first_name }}</td>
                <td>{{ employee.last_name }}</td>
                <td><a href="#" class="btn btn-danger delete"><span class="hide">{{employee.id}}</span> Remove</a></td>
                <td><a href="#" class="btn btn-info update"><span class="hide">{{employee.id}}</span> Update</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

{% block js %}
<script>
    const form = document.querySelector('#form');
    const alertBox = document.querySelector('#alert-box');
    const addEmployeeBtn = document.querySelector('#form_add_employee');
    const UpdateEmployeeBtn = document.querySelector('#form_update_employee')
    const getFirstName = document.querySelector('#id_first_name');
    const getLastName = document.querySelector('#id_last_name');
    const getCsrf = document.getElementsByName('csrfmiddlewaretoken');
    const tbList = document.querySelector('#tbody-list');

    const listUpdateBtns = document.querySelectorAll('.update');

    // Alert message format.
    const msg = (action, content, className) => {
        alertBox.innerHTML = 
        `
        <div class="alert alert-${className} alert-dismissible fade show" role="alert"><b>${action} </b> ${content}</div>
        `
    };
    // Update Employee information:
    for (let i=0; i<listUpdateBtns.length; i++) {
        listUpdateBtns[i].addEventListener('click', (e) => {
            e.preventDefault();

            // hide the form add employees.
            addEmployeeBtn.classList.add('hide');
            
            // display the form update button.
            UpdateEmployeeBtn.classList.remove('hide');

            // set the id value.
            id = listUpdateBtns[i].firstChild.innerHTML;

            // set the data inside FormData function.
            const fd1 = new FormData();
            fd1.append('id', id);
            fd1.append('csrfmiddlewaretoken', getCsrf[0].value);

            // send and recieve the data between the server and the browser using AJAX.
            $.ajax({
                method: 'POST',
                url: 'http://127.0.0.1:8000/employees/info/',
                data: fd1,
                enctype: 'multipart/form-data',
                success: function(success) {

                    // add the values to the inputs when the table update button wqs clicked.
                    getFirstName.value = success['first_name'];
                    getLastName.value = success['last_name'];

                    // if the form update button clicked.
                    UpdateEmployeeBtn.addEventListener('click', (e) => {
                        e.preventDefault();

                         // set the data inside FormData function.
                        const fd2 = new FormData();
                        fd2.append('id', id);
                        fd2.append('first_name', getFirstName.value);
                        fd2.append('last_name', getLastName.value);
                        fd2.append('csrfmiddlewaretoken', getCsrf[0].value);
                        const newListLastName = listUpdateBtns[i].parentElement.previousElementSibling.previousElementSibling;
                        const newListFirstName = listUpdateBtns[i].parentElement.previousElementSibling.previousElementSibling.previousElementSibling;

                        // send and recieve the data between the server and the browser using AJAX.
                        $.ajax({
                            method: 'POST',
                            url: 'http://127.0.0.1:8000/employees/update/',
                            data: fd2,
                            enctype: 'multipart/form-data',
                            success: function(success) {
                                UpdateEmployeeBtn.classList.add('hide');
                                addEmployeeBtn.classList.remove('hide');
                                msg('congratulations', 'Employee info has been update it', 'success');
                                newListFirstName.innerHTML = getFirstName.value;
                                newListLastName.innerHTML = getLastName.value;

                                setTimeout((e) => {
                                    alertBox.innerHTML = "";
                                }, 2000)
                                // setTimeout((e) => {
                                //     getFirstName.value = "";
                                //     getLastName.value = "";
                                // }, 0)
                                
                            },
                            error: function(error) {
                                console.log(error)
                            },
                            cache: false,
                            contentType: false,
                            processData: false,
                        })

                    })
                },
                error: function(error) {
                    console.log(error)
                },
                cache: false,
                contentType: false,
                processData: false,
            })
        })
    }

    // Remove Employee From the list:
    let listRemoveBtns = document.querySelectorAll('.delete');
    for (let i=0; i<listRemoveBtns.length; i++) {
        listRemoveBtns[i].addEventListener('click', (e) => {
            e.preventDefault();
            setTimeout((e) => {
                alertBox.innerHTML = "";
            }, 3000)
            if (confirm(`Are you sure you want to delete this Employee`)) {
                id = listRemoveBtns[i].firstChild.innerHTML
                const fd = new FormData();
                fd.append('id', id);
                fd.append('csrfmiddlewaretoken', getCsrf[0].value)
                $.ajax({
                    method: 'POST',
                    url: 'http://127.0.0.1:8000/employees/delete/',
                    data: fd,
                    enctype: 'multipart/form-data',
                    success: function(success) {
                        // console.log(success);
                        if (success['delete_success']) {
                            listRemoveBtns[i].parentElement.parentElement.remove();
                            msg('congratulations', 'Employee has been deleted from the list', 'success')
                            
                        }else if (success['delete_employee_error']) {
                            msg('Oops!', 'Employee not deleted, Please try again', 'danger')
                        }
                    },
                    error: function(error) {
                        console.log(error);
                    },
                    cache: false,
                    contentType: false,
                    processData: false,
                })
            }
        })
    };




    // Add A new Employee To the List:
    addEmployeeBtn.addEventListener('click', (e) => {
        e.preventDefault();
        const fd = new FormData();
        fd.append('first_name', getFirstName.value);
        fd.append('last_name', getLastName.value);
        fd.append('csrfmiddlewaretoken', getCsrf[0].value);
        if (getFirstName.value && getLastName.value) {
            $.ajax({
                method: 'POST',
                url: 'http://127.0.0.1:8000/employees/list/',
                data: fd,
                enctype: 'multipart/form-data',
                success: function(response) {
                    if (response['success']) {
                        msg('congratulations ^_^ ', response['success'], 'info');
                        setTimeout((e) => {
                            getFirstName.value = "";
                            getLastName.value = "";
                        }, 0)
                        setTimeout((e) => {
                            alertBox.innerHTML = "";
                        }, 3000)
                        const tr = document.createElement('tr');
                        tr.innerHTML =
                        `
                        <tr>
                            <td>${getFirstName.value}</td>
                            <td>${getLastName.value}</td>
                            <td><a href="#" class="btn btn-danger delete"><span class="hide">{{employee.id}}</span> Remove</a></td>
                            <td><a href="#" class="btn btn-info update"><span class="hide">{{employee.id}}</span> Update</a></td>
                        </tr>
                        `;
                        tbList.appendChild(tr);
                    }else if (response['error']) {
                        msg('Oops!', response['error'], 'danger');
                    }
                },
                error: function(error) {
                    console.log('error')
                },
                cache: false,
                contentType: false,
                processData: false,
            })
        }else {
            msg('Oops!',' some Field is Empty','danger')
        }

    });
</script>
{% endblock js %}

employees/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark text-light px-3">
    <a class="navbar-brand" href="#">Employees Management</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'employees:employees_list' %}">Add Employees</a>
        </li>
      </ul>
    </div>
  </nav>